---

- name: chect is it already downloaded or not
  stat:
    path: /opt/apache-tomcat-{{ tomcat_version }}.tar.gz
  register: dwnld
 
- name: download tomcat version
  get_url: url={{ tomcat_url }} dest=/opt/
  when: dwnld.stat.exists == false


- name: chect is it already extracted or not
  stat:
    path: /opt/tomcat/webapps
  register: result

- name: extract tar file
  unarchive: src=/opt/apache-tomcat-{{ tomcat_version }}.tar.gz extra_opts="--strip-components=1" dest=/opt/tomcat remote_src=yes group=tomcat owner=tomcat
  when: result.stat.exists == false
  register: remove
  ignore_errors: true

- name: remove unwanted folders
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/opt/tomcat/webapps/ROOT"
    - "/opt/tomcat/webapps/docs"
    - "/opt/tomcat/webapps/examples"
    - "/opt/tomcat/webapps/manager"
    - "/opt/tomcat/webapps/host-manager"
  when: remove.changed



