---
# tasks file for polyglot.tomcat
#- name: update system
#  yum: name=* state=present

- name: install epel repository && update system
  yum: name=epel-release state=present

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/opt/tomcat createhome=no
  become: yes

- name: Change ownership of Tomcat installation
  file: path=/opt/tomcat/ owner=tomcat group=tomcat  state=directory recurse=yes

- name: Download Tomcat
  import_tasks: download.yml


- name: give read permissinons of conf to tomcat
  file: path=/opt/tomcat/conf mode=0754

- name: copying  Tomcat init script to start tomcat as service
  template: src=tomcat-initscript.sh.j2 dest=/etc/systemd/system/tomcat.service mode=0777

- name: restart Tomcat
  service: name=tomcat state=started enabled=yes


- name: restart Tomcat
  service: name=tomcat state=restarted





